import uuid
from datetime import datetime, timezone

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.orm import Mapped, mapped_column
from pgvector.sqlalchemy import Vector

from app.database import Base


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class VideoEmbedding(Base):
    """the ai's numeric fingerprint for each video's title and description.
    these numbers are what let us find similar videos and group them into clusters."""

    __tablename__ = "video_embeddings"

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    video_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("videos.id", ondelete="CASCADE"), unique=True
    )
    model_name: Mapped[str] = mapped_column(sa.String(100))
    title_embedding: Mapped[list | None] = mapped_column(Vector(384))
    description_embedding: Mapped[list | None] = mapped_column(Vector(384))
    combined_embedding: Mapped[list | None] = mapped_column(Vector(384))
    created_at: Mapped[datetime] = mapped_column(sa.DateTime(timezone=True), default=utcnow)


class Cluster(Base):
    """a bucket of videos that are similar to each other. auto-generated by the ml pipeline.
    the centroid is basically the 'average' of all videos in the group."""

    __tablename__ = "clusters"

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    channel_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("channels.id", ondelete="CASCADE")
    )
    name: Mapped[str | None] = mapped_column(sa.String(255))
    description: Mapped[str | None] = mapped_column(sa.Text)
    algorithm: Mapped[str | None] = mapped_column(sa.String(50))
    n_videos: Mapped[int | None] = mapped_column(sa.Integer)
    avg_views: Mapped[float | None] = mapped_column(sa.Float)
    avg_ctr: Mapped[float | None] = mapped_column(sa.Float)
    centroid: Mapped[list | None] = mapped_column(Vector(384))
    created_at: Mapped[datetime] = mapped_column(sa.DateTime(timezone=True), default=utcnow)


class ClusterMembership(Base):
    """links a video to its cluster and tracks how close a fit it is."""

    __tablename__ = "cluster_memberships"

    __table_args__ = (sa.PrimaryKeyConstraint("cluster_id", "video_id"),)

    cluster_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("clusters.id", ondelete="CASCADE")
    )
    video_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("videos.id", ondelete="CASCADE")
    )
    distance_to_centroid: Mapped[float | None] = mapped_column(sa.Float)


class Prediction(Base):
    """saved result of running a draft title through the title lab —
    what score it got, how it's predicted to perform, and why."""

    __tablename__ = "predictions"

    id: Mapped[uuid.UUID] = mapped_column(sa.Uuid, primary_key=True, default=uuid.uuid4)
    channel_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("channels.id", ondelete="CASCADE")
    )
    input_title: Mapped[str] = mapped_column(sa.Text)
    input_metadata: Mapped[dict | None] = mapped_column(JSONB)
    predicted_performance: Mapped[str | None] = mapped_column(sa.String(20))
    confidence: Mapped[float | None] = mapped_column(sa.Float)
    top_likeness_score: Mapped[float | None] = mapped_column(sa.Float)
    similar_top_clusters: Mapped[dict | None] = mapped_column(JSONB)
    similar_bottom_clusters: Mapped[dict | None] = mapped_column(JSONB)
    reasoning: Mapped[list | None] = mapped_column(ARRAY(sa.Text))
    created_at: Mapped[datetime] = mapped_column(sa.DateTime(timezone=True), default=utcnow)
